pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    AWS_ACCOUNT_ID = "570617927874"
    ECR_REPO = "ml-infer"
    IMAGE_NAME = "ml-infer"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Verify tools') {
      steps {
        sh '''
          set -e
          docker --version
          aws --version
        '''
      }
    }

    stage('AWS Identity') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-cli',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
            set -e
            aws sts get-caller-identity
          '''
        }
      }
    }

    stage('Ensure ECR repo') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-cli',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
            set -e
            aws ecr describe-repositories --repository-names "$ECR_REPO" --region "$AWS_REGION" >/dev/null 2>&1 \
              || aws ecr create-repository --repository-name "$ECR_REPO" --region "$AWS_REGION" >/dev/null
          '''
        }
      }
    }

    stage('Build Docker image') {
      steps {
        sh '''
          set -e
          docker build -t ${IMAGE_NAME}:local -f inference/Dockerfile .
        '''
      }
    }

    stage('Login to ECR') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-cli',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh '''
            set -e
            aws ecr get-login-password --region "$AWS_REGION" \
              | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          '''
        }
      }
    }

    stage('Tag & Push') {
      steps {
        script {
          def shortSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
          env.IMAGE_TAG = "b${env.BUILD_NUMBER}-${shortSha}"
          env.ECR_URI = "${env.AWS_ACCOUNT_ID}.dkr.ecr.${env.AWS_REGION}.amazonaws.com/${env.ECR_REPO}:${env.IMAGE_TAG}"
        }

        sh '''
          set -e
          echo "Pushing: $ECR_URI"
          docker tag ${IMAGE_NAME}:local "$ECR_URI"
          docker push "$ECR_URI"
        '''
      }
    }
  }

  post {
    success {
      echo "ECR image pushed: ${env.ECR_URI}"
    }
  }
}
